global.localStorage = {
  getItem: jest.fn((key) => null),
  setItem: jest.fn(),
  removeItem: jest.fn(),
  clear: jest.fn(),
  key: jest.fn(),
  length: 0,
} as unknown as Storage;

global.chrome = {
  cast: {
    initialize: jest.fn(),
    requestSession: jest.fn(),
    requestSessionById: jest.fn(),
    addReceiverActionListener: jest.fn(),
    removeReceiverActionListener: jest.fn(),
    logMessage: jest.fn(),
    setCustomReceivers: jest.fn(),
    setReceiverDisplayStatus: jest.fn(),
    unescape: jest.fn(),
    AutoJoinPolicy: chrome.cast.AutoJoinPolicy,
    DefaultActionPolicy: chrome.cast.DefaultActionPolicy,
    Capability: chrome.cast.Capability,
    ErrorCode: chrome.cast.ErrorCode,
    ReceiverAction: chrome.cast.ReceiverAction,
    ReceiverAvailability: chrome.cast.ReceiverAvailability,
    SenderPlatform: chrome.cast.SenderPlatform,
    ReceiverType: chrome.cast.ReceiverType,
    SessionStatus: chrome.cast.SessionStatus,
    VERSION: [],
    isAvailable: false,
    ApiConfig: undefined,
    Error: undefined,
    Image: undefined,
    SenderApplication: undefined,
    SessionRequest: undefined,
    Session: undefined,
    Receiver: undefined,
    ReceiverDisplayStatus: undefined,
    Volume: undefined,
    media: undefined
  },
  accessibilityFeatures: {
    spokenFeedback: {
      get: jest.fn(),
      set: jest.fn(),
      clear: jest.fn(),
      onChange: {
        addListener: jest.fn(),
        removeListener: jest.fn(),
        hasListener: jest.fn(),
        getRules: jest.fn(),
        removeRules: jest.fn(),
        addRules: jest.fn(),
        hasListeners: jest.fn(),
      },
    },
    largeCursor: {
      get: jest.fn(),
      set: jest.fn(),
      clear: jest.fn(),
      onChange: {
        addListener: jest.fn(),
        removeListener: jest.fn(),
        hasListener: jest.fn(),
        getRules: jest.fn(),
        removeRules: jest.fn(),
        addRules: jest.fn(),
        hasListeners: function (): boolean {
          throw new Error("Function not implemented.");
        }
      },
    },
    stickyKeys: {
      get: jest.fn(),
      set: jest.fn(),
      clear: jest.fn(),
      onChange: {
        addListener: jest.fn(),
        removeListener: jest.fn(),
        hasListener: jest.fn(),
        getRules: jest.fn(),
        removeRules: jest.fn(),
        addRules: jest.fn(),
        hasListeners: function (): boolean {
          throw new Error("Function not implemented.");
        }
      },
    },
    highContrast: {
      get: jest.fn(),
      set: jest.fn(),
      clear: jest.fn(),
      onChange: {
        addListener: jest.fn(),
        removeListener: jest.fn(),
        hasListener: jest.fn(),
        getRules: jest.fn(),
        removeRules: jest.fn(),
        addRules: jest.fn(),
        hasListeners: function (): boolean {
          throw new Error("Function not implemented.");
        }
      },
    },
    // Repeat for other accessibility features...
  },
  action: {
    disable: jest.fn(),
    enable: jest.fn(),
    getBadgeBackgroundColor: jest.fn(),
    getBadgeText: jest.fn(),
    getPopup: jest.fn(),
    getTitle: jest.fn(),
    setBadgeBackgroundColor: jest.fn(),
    setBadgeText: jest.fn(),
    setIcon: jest.fn(),
    setPopup: jest.fn(),
    setTitle: jest.fn(),
    getBadgeTextColor: jest.fn(),
    getUserSettings: jest.fn(),
    isEnabled: jest.fn(),
    openPopup: jest.fn(),
    setBadgeTextColor: jest.fn(),
    onClicked: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: function (): boolean {
        throw new Error("Function not implemented.");
      }
    },
  },
  alarms: {
    create: jest.fn(),
    getAll: jest.fn(),
    clearAll: jest.fn(),
    clear: jest.fn(),
    get: jest.fn(),
    onAlarm: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: function (): boolean {
        throw new Error("Function not implemented.");
      }
    },
  },
  bookmarks: {
    create: jest.fn().mockImplementation(({ parentId, title, url }) => ({
      id: "mockBookmarkId",
      parentId,
      title,
      url,
    })),
    update: jest.fn().mockImplementation((id, changes) => ({
      id,
      ...changes,
    })),
    getChildren: jest.fn().mockResolvedValue([]),
    remove: jest.fn(),
    removeTree: jest.fn(),
    search: jest.fn(),
    getTree: jest.fn(),
    getRecent: jest.fn(),
    get: jest.fn(),
    move: jest.fn(),
    getSubTree: jest.fn(),
    MAX_WRITE_OPERATIONS_PER_HOUR: 1000,
    MAX_SUSTAINED_WRITE_OPERATIONS_PER_MINUTE: 100,
    onRemoved: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onChanged: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onImportEnded: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onImportBegan: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onMoved: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onCreated: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onChildrenReordered: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
  },
  runtime: {
    id: "mock-extension-id",
    ContextType: {
      BACKGROUND: chrome.runtime.ContextType.BACKGROUND,
      TAB: chrome.runtime.ContextType.TAB,
      POPUP: chrome.runtime.ContextType.POPUP,
      OFFSCREEN_DOCUMENT: chrome.runtime.ContextType.OFFSCREEN_DOCUMENT,
      SIDE_PANEL: chrome.runtime.ContextType.SIDE_PANEL,
    },
    OnInstalledReason: {
      INSTALL: chrome.runtime.OnInstalledReason.INSTALL,
      UPDATE: chrome.runtime.OnInstalledReason.UPDATE,
      CHROME_UPDATE: chrome.runtime.OnInstalledReason.CHROME_UPDATE,
      SHARED_MODULE_UPDATE: chrome.runtime.OnInstalledReason.SHARED_MODULE_UPDATE,
    },
    lastError: undefined,
    getURL: jest.fn((path) => `chrome-extension://${path}`),
    connect: jest.fn(),
    connectNative: jest.fn(),
    getBackgroundPage: jest.fn(),
    getContexts: jest.fn(),
    getManifest: jest.fn(),
    getPackageDirectoryEntry: jest.fn(),
    getPlatformInfo: jest.fn(),
    openOptionsPage: jest.fn(),
    reload: jest.fn(),
    requestUpdateCheck: jest.fn(),
    restart: jest.fn(),
    restartAfterDelay: jest.fn(),
    sendMessage: jest.fn(),
    sendNativeMessage: jest.fn(),
    setUninstallURL: jest.fn(),
    onConnect: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onConnectExternal: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onInstalled: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onMessage: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onMessageExternal: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onRestartRequired: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onStartup: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onSuspend: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onSuspendCanceled: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onUpdateAvailable: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onBrowserUpdateAvailable: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onUserScriptConnect: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onUserScriptMessage: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
  },
  storage: {
    AccessLevel: {
      TRUSTED_AND_UNTRUSTED_CONTEXTS: "TRUSTED_AND_UNTRUSTED_CONTEXTS",
      TRUSTED_CONTEXTS: "TRUSTED_CONTEXTS",
    },
    local: {
      get: jest.fn().mockImplementation((keys, callback) => {
        const data = { BOOKMARK_PARENT_ID: "default_parent_id" };
        if (callback) callback(data);
        return Promise.resolve(data);
      }),
      set: jest.fn().mockImplementation((items, callback) => {
        if (callback) callback();
        return Promise.resolve();
      }),
      remove: jest.fn().mockImplementation((keys, callback) => {
        if (callback) callback();
        return Promise.resolve();
      }),
      clear: jest.fn().mockImplementation((callback) => {
        if (callback) callback();
        return Promise.resolve();
      }),
      QUOTA_BYTES: 102400,
      getBytesInUse: jest.fn().mockResolvedValue(0),
      setAccessLevel: jest.fn(),
      onChanged: {
        addListener: jest.fn(),
        removeListener: jest.fn(),
        hasListener: jest.fn(),
        getRules: jest.fn(),
        removeRules: jest.fn(),
        addRules: jest.fn(),
        hasListeners: jest.fn(),
      },
    },
    sync: {
      get: jest.fn(),
      set: jest.fn(),
      remove: jest.fn(),
      clear: jest.fn(),
      QUOTA_BYTES: 102400,
      QUOTA_BYTES_PER_ITEM: 8192,
      MAX_ITEMS: 512,
      MAX_WRITE_OPERATIONS_PER_HOUR: 1800,
      MAX_SUSTAINED_WRITE_OPERATIONS_PER_MINUTE: 120,
      MAX_WRITE_OPERATIONS_PER_MINUTE: 120,
      getBytesInUse: jest.fn(),
      setAccessLevel: jest.fn(),
      onChanged: {
        addListener: jest.fn(),
        removeListener: jest.fn(),
        hasListener: jest.fn(),
        getRules: jest.fn(),
        removeRules: jest.fn(),
        addRules: jest.fn(),
        hasListeners: jest.fn(),
      },
    },
    managed: {
      get: jest.fn(),
      getBytesInUse: jest.fn(),
      clear: jest.fn(),
      set: jest.fn(),
      remove: jest.fn(),
      setAccessLevel: jest.fn(),
      onChanged: {
        addListener: jest.fn(),
        removeListener: jest.fn(),
        hasListener: jest.fn(),
        getRules: jest.fn(),
        removeRules: jest.fn(),
        addRules: jest.fn(),
        hasListeners: jest.fn(),
      },
    },
    session: {
      get: jest.fn(),
      set: jest.fn(),
      remove: jest.fn(),
      clear: jest.fn(),
      QUOTA_BYTES: 102400,
      getBytesInUse: jest.fn(),
      setAccessLevel: jest.fn(),
      onChanged: {
        addListener: jest.fn(),
        removeListener: jest.fn(),
        hasListener: jest.fn(),
        getRules: jest.fn(),
        removeRules: jest.fn(),
        addRules: jest.fn(),
        hasListeners: jest.fn(),
      },
    },
    onChanged: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
  },
  tabs: {
    query: jest.fn().mockResolvedValue([
      { id: 1, url: "https://example.com", pinned: false },
    ]),
    executeScript: jest.fn(),
    get: jest.fn(),
    getAllInWindow: jest.fn(),
    getCurrent: jest.fn(),
    getSelected: jest.fn(),
    remove: jest.fn(),
    captureVisibleTab: jest.fn(),
    reload: jest.fn(),
    duplicate: jest.fn(),
    sendMessage: jest.fn(),
    sendRequest: jest.fn(),
    connect: jest.fn(),
    create: jest.fn(),
    move: jest.fn(),
    update: jest.fn(),
    insertCSS: jest.fn(),
    highlight: jest.fn(),
    detectLanguage: jest.fn(),
    setZoom: jest.fn(),
    getZoom: jest.fn(),
    setZoomSettings: jest.fn(),
    getZoomSettings: jest.fn(),
    discard: jest.fn(),
    goForward: jest.fn(),
    goBack: jest.fn(),
    group: jest.fn(),
    ungroup: jest.fn(),
    onHighlighted: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onRemoved: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onCreated: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onActivated: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onReplaced: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onSelectionChanged: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onUpdated: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onAttached: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onMoved: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onDetached: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onActiveChanged: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onHighlightChanged: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onZoomChange: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    TAB_ID_NONE: -1 as const,
  },
  windows: {
    get: jest.fn().mockResolvedValue({ id: 1 }),
    create: jest.fn().mockResolvedValue({ id: 1 }),
    getCurrent: jest.fn(),
    getAll: jest.fn(),
    update: jest.fn(),
    remove: jest.fn(),
    getLastFocused: jest.fn(),
    WINDOW_ID_CURRENT: -2 as const,
    WINDOW_ID_NONE: -1 as const,
    onRemoved: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onFocusChanged: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onBoundsChanged: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
    onCreated: {
      addListener: jest.fn(),
      removeListener: jest.fn(),
      hasListener: jest.fn(),
      getRules: jest.fn(),
      removeRules: jest.fn(),
      addRules: jest.fn(),
      hasListeners: jest.fn(),
    },
  },
};

(global as any).CONFIG_RO = {
  BOOKMARK_PARENT_ID: jest.fn().mockResolvedValue("default_parent_id"),
  INSTANCE_ID: jest.fn().mockResolvedValue("mock_instance_id"),
};
